apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: firstpod
  name: firstpod
spec:
  containers:
  - image: nithya890/first:1.0
    name: firstpod
    ports:
    - containerPort: 8080
    resources:
      resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 300Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
