apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    run: firstpod
spec:
  containers:
  - name: firstpod
    image: nithya890/first:1.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
